services:
  lab2:
    image: fantoni1/lab2-inf-unipi:latest
    container_name: lab2
    volumes:
      - ./data/:/home/user
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    ports:
      - 2222:22
